name: Build container image

on:
  push:
  pull_request:

jobs:
  container-image-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: true

      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract repo name
        id: repo_name_step
        run: |
          REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "repo_name=ghcr.io/$REPO_LOWERCASE" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: true
          tags: |
            ghcr.io/${{ steps.repo_name_step.outputs.repo_name }}:${{ github.sha }}
